---
{{- $namespace := .Values.namespace }}
{{ with .Values.eurekaServer }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: {{ $namespace }}
  labels:
    app: eureka-server-deployment
spec:
  selector:
    matchLabels:
        app: eureka-server-deployment
  template:
    metadata:
        labels:
            app: eureka-server-deployment
    spec:
      containers:
        - name: eureka-server
          image: {{ .image }}
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: {{ $namespace }}
  labels:
    app: eureka-server-deployment
spec:
  selector:
    app: eureka-server-deployment
  ports:
    - protocol: TCP
      port: {{ .port }}
  type: LoadBalancer
{{- end }}
---
{{ with .Values.apiGateway }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: {{ $namespace }}
  labels:
    app: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway-deployment
  template:
    metadata:
      labels:
        app: api-gateway-deployment
    spec:
      containers:
        - name: api-gateway
          image: {{ .image }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ $namespace }}
  labels:
    app: api-gateway-deployment
spec:
  selector:
    app: api-gateway-deployment
  ports:
    - protocol: TCP
      port: {{ .port }}
{{ end }}
---
{{ with .Values.zookeeper }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: {{ $namespace }}
  labels:
    app: zookeeper-deployment
spec:
  selector:
    matchLabels:
        app: zookeeper-deployment
  template:
    metadata:
      labels:
        app: zookeeper-deployment
    spec:
      containers:
        - name: zookeeper
          image: {{ .image }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: {{ $namespace }}
  labels:
    app: zookeeper-deployment
spec:
  selector:
    app: zookeeper-deployment
  ports:
    - protocol: TCP
      port: {{ .port }}
  type: ClusterIP
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-configmap
data:
  kafka-topics.sh: |-
    BOOTSTRAP_SERVER=${1:-localhost:29092}
    PARTITIONS=${2:-3}
    kafka-topics --list --bootstrap-server $BOOTSTRAP_SERVER
    kafka-topics --alter --topic account_created.account.appointment_outbox --partitions $PARTITIONS --bootstrap-server $BOOTSTRAP_SERVER
    kafka-topics --alter --topic appointment_created.appointment.appointment_outbox --partitions $PARTITIONS --bootstrap-server $BOOTSTRAP_SERVER
    kafka-topics --alter --topic pet_created.pet.appointment_outbox --partitions $PARTITIONS --bootstrap-server $BOOTSTRAP_SERVER
    kafka-topics --alter --topic availability_request.appointment.availability_outbox --partitions $PARTITIONS --bootstrap-server $BOOTSTRAP_SERVER
    kafka-topics --alter --topic availability_response.availability.appointment_outbox --partitions $PARTITIONS --bootstrap-server $BOOTSTRAP_SERVER
    kafka-topics --alter --topic payment_request.appointment.payment_outbox --partitions $PARTITIONS --bootstrap-server $BOOTSTRAP_SERVER
    kafka-topics --alter --topic payment_response.payment.appointment_outbox --partitions $PARTITIONS --bootstrap-server $BOOTSTRAP_SERVER
---
{{ with .Values.kafkaBroker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-deployment
  namespace: {{ $namespace }}
  labels:
    app: kafka-broker-deployment
spec:
  selector:
    matchLabels:
        app: kafka-broker-deployment
  template:
    metadata:
      labels:
        app: kafka-broker-deployment
    spec:
      containers:
        - name: kafka-broker
          image: {{ .image }}
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
      volumes:
        - name: script-volume
          configMap:
            name: script-configmap
            defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
  namespace: {{ $namespace }}
  labels:
    app: kafka-broker-deployment
spec:
  selector:
    app: kafka-broker-deployment
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
  type: ClusterIP
{{- end }}
---
{{- with .Values.schemaRegistry }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
  namespace: {{ $namespace }}
  labels:
    app: schema-registry-deployment
spec:
  selector:
    matchLabels:
      app: schema-registry-deployment
  template:
    metadata:
      labels:
        app: schema-registry-deployment
    spec:
      containers:
        - name: schema-registry
          image: {{ .image }}
          env:
              {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
              {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  namespace: {{ $namespace }}
  labels:
    app: schema-registry-deployment
spec:
  selector:
    app: schema-registry-deployment
  ports:
    - protocol: TCP
      port: {{ .port }}
  type: ClusterIP
{{- end}}
---
{{- with .Values.kafkaUi }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  namespace: {{ $namespace }}
  labels:
    app: kafka-ui-deployment
spec:
  selector:
    matchLabels:
      app: kafka-ui-deployment
  template:
    metadata:
      labels:
        app: kafka-ui-deployment
    spec:
      containers:
        - name: kafka-ui
          image: {{ .image }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: {{ $namespace }}
  labels:
    app: kafka-ui-deployment
spec:
  selector:
    app: kafka-ui-deployment
  ports:
    - protocol: TCP
      port: {{ .port }}
  type: LoadBalancer
{{- end }}
---
{{ with .Values.debeziumConnect }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect-deployment
  namespace: {{ $namespace }}
  labels:
    app: debezium-connect-deployment
spec:
  selector:
    matchLabels:
      app: debezium-connect-deployment
  template:
    metadata:
      labels:
        app: debezium-connect-deployment
    spec:
      containers:
        - name: debezium-connect
          image: {{ .image }}
          env:
            {{- range .env }}
              - name: {{ .name }}
                value: {{ .value | quote }}
              {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  namespace: {{ $namespace }}
  labels:
      app: debezium-connect-deployment
spec:
  selector:
    app: debezium-connect-deployment
  ports:
    - protocol: TCP
      port: {{ .port }}
  type: LoadBalancer
{{- end }}