/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vet.appointment.system.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreatePetEventAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1484980113459675389L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreatePetEventAvroModel\",\"namespace\":\"com.vet.appointment.system.kafka.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"ownerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"species\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"birthDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreatePetEventAvroModel> ENCODER =
      new BinaryMessageEncoder<CreatePetEventAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreatePetEventAvroModel> DECODER =
      new BinaryMessageDecoder<CreatePetEventAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreatePetEventAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreatePetEventAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreatePetEventAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreatePetEventAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreatePetEventAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreatePetEventAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreatePetEventAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreatePetEventAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String ownerId;
  private java.lang.String name;
  private java.lang.String species;
  private java.lang.String birthDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreatePetEventAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param ownerId The new value for ownerId
   * @param name The new value for name
   * @param species The new value for species
   * @param birthDate The new value for birthDate
   */
  public CreatePetEventAvroModel(java.lang.String id, java.lang.String ownerId, java.lang.String name, java.lang.String species, java.lang.String birthDate) {
    this.id = id;
    this.ownerId = ownerId;
    this.name = name;
    this.species = species;
    this.birthDate = birthDate;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return ownerId;
    case 2: return name;
    case 3: return species;
    case 4: return birthDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: ownerId = value$ != null ? value$.toString() : null; break;
    case 2: name = value$ != null ? value$.toString() : null; break;
    case 3: species = value$ != null ? value$.toString() : null; break;
    case 4: birthDate = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'ownerId' field.
   * @return The value of the 'ownerId' field.
   */
  public java.lang.String getOwnerId() {
    return ownerId;
  }


  /**
   * Sets the value of the 'ownerId' field.
   * @param value the value to set.
   */
  public void setOwnerId(java.lang.String value) {
    this.ownerId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'species' field.
   * @return The value of the 'species' field.
   */
  public java.lang.String getSpecies() {
    return species;
  }


  /**
   * Sets the value of the 'species' field.
   * @param value the value to set.
   */
  public void setSpecies(java.lang.String value) {
    this.species = value;
  }

  /**
   * Gets the value of the 'birthDate' field.
   * @return The value of the 'birthDate' field.
   */
  public java.lang.String getBirthDate() {
    return birthDate;
  }


  /**
   * Sets the value of the 'birthDate' field.
   * @param value the value to set.
   */
  public void setBirthDate(java.lang.String value) {
    this.birthDate = value;
  }

  /**
   * Creates a new CreatePetEventAvroModel RecordBuilder.
   * @return A new CreatePetEventAvroModel RecordBuilder
   */
  public static com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder newBuilder() {
    return new com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder();
  }

  /**
   * Creates a new CreatePetEventAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreatePetEventAvroModel RecordBuilder
   */
  public static com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder newBuilder(com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder other) {
    if (other == null) {
      return new com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder();
    } else {
      return new com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CreatePetEventAvroModel RecordBuilder by copying an existing CreatePetEventAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CreatePetEventAvroModel RecordBuilder
   */
  public static com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder newBuilder(com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel other) {
    if (other == null) {
      return new com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder();
    } else {
      return new com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreatePetEventAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreatePetEventAvroModel>
    implements org.apache.avro.data.RecordBuilder<CreatePetEventAvroModel> {

    private java.lang.String id;
    private java.lang.String ownerId;
    private java.lang.String name;
    private java.lang.String species;
    private java.lang.String birthDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ownerId)) {
        this.ownerId = data().deepCopy(fields()[1].schema(), other.ownerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.species)) {
        this.species = data().deepCopy(fields()[3].schema(), other.species);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[4].schema(), other.birthDate);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing CreatePetEventAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ownerId)) {
        this.ownerId = data().deepCopy(fields()[1].schema(), other.ownerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.species)) {
        this.species = data().deepCopy(fields()[3].schema(), other.species);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.birthDate)) {
        this.birthDate = data().deepCopy(fields()[4].schema(), other.birthDate);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ownerId' field.
      * @return The value.
      */
    public java.lang.String getOwnerId() {
      return ownerId;
    }


    /**
      * Sets the value of the 'ownerId' field.
      * @param value The value of 'ownerId'.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder setOwnerId(java.lang.String value) {
      validate(fields()[1], value);
      this.ownerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ownerId' field has been set.
      * @return True if the 'ownerId' field has been set, false otherwise.
      */
    public boolean hasOwnerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ownerId' field.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder clearOwnerId() {
      ownerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'species' field.
      * @return The value.
      */
    public java.lang.String getSpecies() {
      return species;
    }


    /**
      * Sets the value of the 'species' field.
      * @param value The value of 'species'.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder setSpecies(java.lang.String value) {
      validate(fields()[3], value);
      this.species = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'species' field has been set.
      * @return True if the 'species' field has been set, false otherwise.
      */
    public boolean hasSpecies() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'species' field.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder clearSpecies() {
      species = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'birthDate' field.
      * @return The value.
      */
    public java.lang.String getBirthDate() {
      return birthDate;
    }


    /**
      * Sets the value of the 'birthDate' field.
      * @param value The value of 'birthDate'.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder setBirthDate(java.lang.String value) {
      validate(fields()[4], value);
      this.birthDate = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'birthDate' field has been set.
      * @return True if the 'birthDate' field has been set, false otherwise.
      */
    public boolean hasBirthDate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'birthDate' field.
      * @return This builder.
      */
    public com.vet.appointment.system.kafka.avro.model.CreatePetEventAvroModel.Builder clearBirthDate() {
      birthDate = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreatePetEventAvroModel build() {
      try {
        CreatePetEventAvroModel record = new CreatePetEventAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.ownerId = fieldSetFlags()[1] ? this.ownerId : (java.lang.String) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.species = fieldSetFlags()[3] ? this.species : (java.lang.String) defaultValue(fields()[3]);
        record.birthDate = fieldSetFlags()[4] ? this.birthDate : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreatePetEventAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreatePetEventAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreatePetEventAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CreatePetEventAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










