
# Application config
server:
  port: 8183

# Service registry
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost}:8761/eureka
  instance:
    prefer-ip-address: true

# Database
spring:
  application:
    name: "appointment-service"
  jpa:
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/postgres?stringtype=unspecified&currentSchema=appointment
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:init-schema.sql
      mode: always
      platform: postgres
      data-locations: classpath:init-data.sql

# Kafka
kafka-config-data:
  bootstrap-server: ${KAFKA_BOOTSTRAP_HOST:localhost}:${KAFKA_BOOTSTRAP_PORT:29092}
  schema-registry-url: ${SCHEMA_REGISTRY_HOST:http://localhost}:8081
  schema-registry-url-key: schema.registry.url

kafka-producer-data:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer

kafka-consumer-data:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true

kafka-consumer-topic-name:
  account-created-event: account_created.account.appointment_outbox
  pet-created-event: pet_created.pet.appointment_outbox
  availability-response-event: availability_response.availability.appointment_outbox
  payment-response-event: payment_response.payment.appointment_outbox

kafka-consumer-group-id:
  availability-group-id: availability-topic-consumer
  payment-group-id: payment-topic-consumer
